In [ ]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer  , CountVectorizer #for vectorization of documents
#from sklearn.metrics.pairwise import cosine_similarity # for checking text similarity btn jd and cvs
from nltk.stem.wordnet import WordNetLemmatizer # for getting root word through lemmatization
from nltk.corpus import stopwords as stp # to get stopwords for future removal from the docs
#import vec_lemma as lemma #comes with lemmatization and vectorization
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize
nltk.download('stopwords')

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")




[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
data = pd.read_csv('Train.csv',header = 0)

In [ ]:
data.head(5)

ID                                             Tweets  Labels
0   2  So chuga si tunakutana kesho kwenye Nyamachoma...       0
1   3     Asante sana watu wa Sirari jimbo la Tarime ...       1
2   5     Leo nimepata kitambulisho changu cha taifa ...       1
3   6                 Mgema akisifiwa tembo hulitia maji       0
4   8  Ee Mwenyezi Mungu Msamehe na Umrehemu na Umuaf...       1

In [ ]:
def clean_text(words):
    """
    Text cleaning
    Returns a cleaned text
    """
    words = str(words).lower()
    
    # new line removal#
    words = re.sub("\n" , " " , words)
    words = re.sub(u"\xa0" , " " , words)
    words = re.sub('[^A-Za-z0-9]+\s+', ' ', words)
    words = re.sub('\!', ' ', words)
    words = re.sub('\,', ' ', words)
    # remove distracting single quotes
    words = re.sub("\'", "", words)
    words = "".join(words)
    return words

In [ ]:
data['Tweets'] = data['Tweets'].apply(clean_text)
data.head()

ID                                             Tweets  Labels
0   2  so chuga si tunakutana kesho kwenye nyamachoma...       0
1   3   asante sana watu wa sirari jimbo la tarime vi...       1
2   5   leo nimepata kitambulisho changu cha taifa as...       1
3   6                 mgema akisifiwa tembo hulitia maji       0
4   8  ee mwenyezi mungu msamehe na umrehemu na umuaf...       1

In [ ]:
data.shape

(2263, 3)

In [ ]:
data2 = pd.read_csv('Test.csv',header = 0)
data2.head()

ID                                             Tweets
0   4     Maandalizi Wadau kutoka Kamati ya Maandaliz...
1   7  Tunashukuru sana kwa mrejesho wako kuhusiana n...
2   9              Asante kwa kutembelea kurasa yetu  CM
3  10  Habari Asante kwa kutuandikia kupitia kurasa z...
4  15     Kunawa sio wakati wa kula tutujiwekee tarat...

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
y = data.Labels


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data['Tweets'], y,test_size=0.2, random_state=42)
X_train.head()

316      liverpool imethibitisha kuwa kiungo wa kati f...
611     rich habaritunapenda kukujulisha kwamba tumefa...
1893     jionee mwenyewe taswira mbalimbali jinsi kazi...
427     habari ahsante kwa kuwasiliana nasi tunaomba u...
374      bro na sister nawaona peace xna zero majivuno...
Name: Tweets, dtype: object

In [ ]:

# Initialize a CountVectorizer object: count_vectorizer
count_vectorizer = CountVectorizer()

# Transform the training data using only the 'text' column values: count_train 
count_train = count_vectorizer.fit_transform(X_train)

# Transform the test data using only the 'text' column values: count_test 
count_test = count_vectorizer.transform(X_test)

# Print the first 10 features of the count_vectorizer
print(count_vectorizer.get_feature_names()[:10])

['00itakuwaje', '01', '01082019', '02', '03', '05', '062020', '0624613046', '0654', '0655']


In [ ]:
# Initialize a TfidfVectorizer object: tfidf_vectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.7)

# Transform the training data: tfidf_train 
tfidf_train = tfidf_vectorizer.fit_transform(X_train)

# Transform the test data: tfidf_test 
tfidf_test = tfidf_vectorizer.transform(X_test)

# Print the first 10 features
print(tfidf_vectorizer.get_feature_names()[:10])


['00itakuwaje', '01', '01082019', '02', '03', '05', '062020', '0624613046', '0654', '0655']


In [ ]:
# Import the necessary modules
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB

# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(count_train,y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(count_test)

# Calculate the accuracy score: score
score = metrics.accuracy_score(y_test,pred)
print(score)

# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test,pred)
print(cm)


0.6114790286975718
[[  0  38   8]
 [  0 224  40]
 [  0  90  53]]


In [ ]:
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(count_train,y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(count_test)

# Calculate the accuracy score: score
score = metrics.accuracy_score(y_test,pred)
print(score)

# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test,pred)
print(cm)
pred


0.6114790286975718
[[  0  38   8]
 [  0 224  40]
 [  0  90  53]]


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,

In [ ]:
# Import the necessary modules
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB

# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(tfidf_train,y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(tfidf_test)

# Calculate the accuracy score: score
score = metrics.accuracy_score(y_test,pred)
print(score)

# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test,pred)
print(cm)


0.5827814569536424
[[  0  45   1]
 [  0 262   2]
 [  0 141   2]]


In [ ]:
# Initialize a CountVectorizer object: count_vectorizer
count_vectorizer = CountVectorizer()

# Transform the training data using only the 'text' column values: count_train 
count_train1 = count_vectorizer.fit_transform(X_train)
x_train = data2['Tweets']
# Transform the test data using only the 'text' column values: count_test 
count_test2 = count_vectorizer.transform(x_train)

# Print the first 10 features of the count_vectorizer
print(count_vectorizer.get_feature_names()[:10])

['00itakuwaje', '01', '01082019', '02', '03', '05', '062020', '0624613046', '0654', '0655']


In [ ]:
count_test2

<755x8936 sparse matrix of type '<class 'numpy.int64'>'
	with 9240 stored elements in Compressed Sparse Row format>

In [ ]:
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(count_train,y_train)

# Create the predicted tags: pred
pred1 = nb_classifier.predict(count_test2)
pred1


array([ 0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0,  1,  1,  1,  0,  1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  1,
        0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  1,  0,  0,
        0,  1,  0,  1,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  0,  1,  0,
        1,  1,  0,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  0,  0,  0,  1,  0,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  1

In [ ]:
data = {'ID': data2['ID'], 'Labels': pred1}
# Create DataFrame.
df = pd.DataFrame(data)
# Print the output.
print(df)


       ID  Labels
0       4       0
1       7       1
2       9       1
3      10       0
4      15       0
..    ...     ...
750  3004       0
751  3005       0
752  3007       0
753  3015       0
754  3019       0

[755 rows x 2 columns]


In [ ]:
data2.shape

(755, 2)

In [ ]:
df.to_csv('sample_submission.csv', index=False)

In [ ]:
data2.head()

ID                                             Tweets
0   4     Maandalizi Wadau kutoka Kamati ya Maandaliz...
1   7  Tunashukuru sana kwa mrejesho wako kuhusiana n...
2   9              Asante kwa kutembelea kurasa yetu  CM
3  10  Habari Asante kwa kutuandikia kupitia kurasa z...
4  15     Kunawa sio wakati wa kula tutujiwekee tarat...